### ISSUE TITLE
highlight matching parens and brackets

### ISSUE THREAD

**Issue by champoll** [nyusemantics/LambdaCalculatorPublic#11]
(Request inspired by a suggestion by Peter Khoury, and by TexShop's behavior)

Highlight matching parens and brackets. For example, when typing a closing paren, briefly highlight the matching open paren. When placing the cursor at any paren that has a matching paren, briefly highlight that or both.

**Comment by RTKno1** [comment]
This request has been implemented as of version 2.6.0.
